language: node_js
sudo: required
dist: xenial
node_js: stable

before_install:
- npm install
- npm install hexo-cli
- npm install hexo-deployer-git
- npm install gulp

install:
- npm install gulp-htmlclean
- npm install gulp-htmlmin
- npm install gulp-clean-css
- npm install gulp-uglify
- npm install gulp-imagemin

script:
- hexo clean
- hexo generate
- gulp

after_script:
- cd ./public
- git init
- git config user.name "srcrs"
- git config user.email "531238678@qq.com"
- git add .
- git commit -m "自动部署"
- git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REP}" master:master 

branches:
  only:
  - hexo


env:
  global:
    - GITHUB_REP: github.com/srcrs/srcrs.github.io.git