language: node_js

sudo: required
dist: xenial

node_js: stable

#install:
#  - npm install

branches:
  only:
    - hexo

before_install: 
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli
  - npm install gulp

#  - sudo apt-get install libpng16-dev
install:
  - npm install
  - npm install gulp-htmlclean
  - npm install gulp-htmlmin
  - npm install gulp-clean-css
  - npm install gulp-uglify
  - npm install gulp-imagemin

script:
  - hexo clean
  - hexo generate
  - gulp
  - hexo d


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: master
  on:
    branch: hexo