language: node_js
sudo: required
dist: xenial
node_js: stable

before_install:
- openssl aes-256-cbc -K $encrypted_73b0318d1980_key -iv $encrypted_73b0318d1980_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "srcrs"
- git config --global user.email "531238678@qq.com"

install:
- npm install
- npm install hexo-cli
- npm install hexo-deployer-git
- npm install gulp
- npm install gulp-htmlclean
- npm install gulp-htmlmin
- npm install gulp-clean-css
- npm install gulp-uglify
- npm install gulp-imagemin

script:
- hexo clean
- hexo generate
- gulp
- hexo deploy