version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      # connect to github by ssh
      - add_ssh_keys:
          fingerprints:
          - $FPS
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          git config --global user.email "srcrs@foxmail.com"
          git config --global user.name "srcrs"
          git checkout gh-pages
          git reset --hard origin/main
          npm run build
          git add .
          git commit -m "auto build"
          git push -f --set-upstream origin gh-pages

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
