version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    filters:
      branches:
        only: main
    steps:
      # connect to github by ssh
      - add_ssh_keys:
          fingerprints:
          - $FPS
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          git config --global user.email "srcrs@foxmail.com"
          git config --global user.name "srcrs"
          git pull
          git checkout -b gh-pages
          npm run build
          git checkout gh-pages
          git add .
          git commit -m "update title"
          git push
