name: scrrs deployer # Actions 名字

on: 
  push:
    branches:
      - vue

jobs:
  build: 
    name: Build and publish
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Setup Environmental Science 
        run: |
           npm install -g vuepress
           npm install

      - name: Generate public files 
        run: |
          npm run build 

      - name: Deploy
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GE_TOKEN: ${{ secrets.GE_TOKEN }}
          GH_REP: ${{ secrets.GH_REP }}
          GE_REP: ${{ secrets.GE_REP }}
        run: |
          cd ./public
          git init
          git config user.name "srcrs"
          git config user.email "531238678@qq.com"
          git add .
          git commit -m "自动部署"
          git push --force --quiet "https://${GH_TOKEN}@${GH_REP}" master:master
          git push --force --quiet "https://${GE_TOKEN}@${GE_REP}" master:master
    